apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::534118859666:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1R3C2KK9TMQR4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::534118859666:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-25T02:03:25Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-02-25T02:03:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1723"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e5bfbf8c-97e3-4d41-a2f3-3be5c45446d3
